### ISSUE TITLE
tadpole docker container 재시작시 기존에 설정해둔 DB(maria DB) 관련 JAR파일 오류 발생

### ISSUE THREAD

**Issue by jaekwon-park** [hangum/docker-TadpoleDBHub#7]
## 개요
Tadpole docker container 재시작시 기존에 설정해둔 DB 관련한 JAR 파일 오류가 나면서 database 접속이 안되는 문제가 있습니다. 

일단 문제가 되는건 Mariadb-java-client-2.2.1.jar 파일이 오류(새로운 jar 파일을 업로드 하라는 메시지가 나옴)가 나면서 기존에 설정해둔 DB 접속이 되질 않습니다. 

일단 해결책으로는 기존 실행된 docker container를 완전 삭제후 새로 docker container를 실행하면 다시 정상적으로 DB접속이 가능합니다. 

## 이슈 재현

`# wget https://raw.githubusercontent.com/hangum/docker-TadpoleDBHub/master/docker-compose.yml`
`# docker-compose up -d `

tadpole 셋팅 및 Database 셋팅 후 아래 명령어 실행
`# docker restart $(docker ps | grep hyunjongcho/tadpoledbhub | awk '{print $1}')`

tadpole web page 접속해서 셋팅한 Database 접속 시도

## 이슈 해결 방법
`# docker-compose down`
`# docker-compose up -d `

**Comment by hangum** [comment]
네. 명시적으로 마리아 디비 드라이버를 추가해 놓도록 하겠습니다.

**Comment by hangum** [comment]
엔터버전에는 이미 수정되었고, 오픈소스 버전에도 수정했습니다. 감사합니다.

**Comment by jaekwon-park** [comment]
혹시 수정 반영된 Docker  Container 버전 tag가 1.8.4r0 인가요?

**Comment by hangum** [comment]
아직 전이에요.최신버전 빌드해서 사무실 들어가는데로 작업해 놓을게요. 

나의 iPhone에서 보냄

2018. 7. 2. 오후 2:20, Jaekwon Park <notifications@github.com> 작성:

**Comment by hangum** [comment]
@jaekwon-park  서버에 반영되었습니다.
